### ISSUE TITLE
Add GeoJSON output format support

### ISSUE THREAD

**Issue by mpiannucci** [xpublish-community/xpublish-edr#50]
This is more common than CovJSON and allows you to directly visualize on many mapping projects without custom parsers

**Comment by mpiannucci** [comment]
There are like a billion different ways to do this... the simplest adding a geopandas or geojson dep or we can just hand roll it. 

Does anyone have strong opinions?

**Comment by dcherian** [comment]
I like the idea of just using geopandas. Seems easiest in the long-run, and its a pretty stable well-liked project.
